### ISSUE TITLE
64位进程的输入表和32位进程不一致

### ISSUE THREAD

**Issue by yingchengpa** [JelinYao/dependency#4]
同一个程序，使用32位编译和64位编译，使用项目显示内容不一致，使用微软的depends正常，如图介绍：

A： 使用depends.exe 打开64位进程，显示的输入表函数正常
B：使用dependency.exe 打开64位进程，只显示一个函数
C： 使用dependecy.exe 打开32位进程，显示的函数正常

![Snipaste_2023-01-27_20-20-06](https://user-images.githubusercontent.com/6310830/215086494-678eb9fa-5ca5-4f57-95f1-5f77e8b5e578.png)

**Comment by JelinYao** [comment]
确实是个bug，64位PE文件读取导入表使用的是32位接口导致的。问题已修复，可以使用最新的64位程序查看：https://github.com/JelinYao/dependency/releases/download/1.5/dependency_x64.7z
32位的还有问题，因为发现一个很奇怪的现象：
64位系统下，32位程序读取C:\Windows\System32下面的PE文件，解析出来竟然是32位PE（实际为64位程序）；将C:\Windows\System32下面的PE文件拷贝到桌面，再用32位程序读取，解析出来是64位PE（这才是正常）。
也就是说，同一个64位PE文件，在系统目录和其他目录，32位的dependency程序解析出来的PE文件头中PE架构不一致。怀疑是读取文件的时候操作系统用了缓存，但是查了相关API没有找到佐证。

**Comment by yingchengpa** [comment]
多谢。现在用python的pefile模块更加简单。
