### ISSUE TITLE
32bit or 64bit

### ISSUE THREAD

**Issue by Git-Kevin** [JelinYao/dependency#5]
Could you please add a flag to show how many bits about this lib? Such as 32 or 64. Thanks!

**Comment by JelinYao** [comment]
Do you mean this?
32bits GDI32.dll in C:\Windows\SysWOW64
![image](https://user-images.githubusercontent.com/7205249/228886030-48d15a70-82ab-4749-8bfc-9f7ecc343245.png)
64bits GDI32.dll in C:\Windows\System32
![1](https://user-images.githubusercontent.com/7205249/228886251-6bf08caa-2b10-4b37-adf1-395663c20c16.png)

**Comment by Git-Kevin** [comment]
So sorry, I didn't note that feature is at the top of the window. Thanks a lot!
