### ISSUE TITLE
一些动态库的后缀不一定是dll，可否添加打开支持

### ISSUE THREAD

**Issue by WangTingMan** [JelinYao/dependency#6]
如题

**Comment by JelinYao** [comment]
是支持的，两种方式打开
1.直接把PE文件拖入
2.菜单打开选择筛选：所有文件
![QQ图片20230330230959](https://user-images.githubusercontent.com/7205249/228883296-a35d638c-19fc-4ec3-abb2-07afb6fc956f.png)
