### ISSUE TITLE
增加右键菜单

### ISSUE THREAD

**Issue by xuxian02092213** [JelinYao/dependency#7]
兄弟，还在维护吗？
非常不错的东西，我在你代码基础上，在帮助里面增加了一个菜单项，可以类似以前的vc6那样，可以在exe、dll上右键，直接打开dependency，还增加了右键菜单拷贝函数功能，如果还维护的话，可以合并一下吗
[Uploading dependency.zip…]()

**Comment by JelinYao** [comment]
可以的啊，你的代码怎么合入呢？

**Comment by xuxian02092213** [comment]
我就改了几个文件，在附件里面，你能看见我上传的附件嘛？

**Comment by JelinYao** [comment]
看得见，但是点击了没法下载

**Comment by xuxian02092213** [comment]
[dependency.zip](https://github.com/JelinYao/dependency/files/13407917/dependency.zip)

**Comment by JelinYao** [comment]
1.6版本已经加进去了，感谢你的支持。
