### ISSUE TITLE
你有两个文件没提交

### ISSUE THREAD

**Issue by eachcan** [JelinYao/dependency#8]
![image](https://github.com/JelinYao/dependency/assets/1684101/36e8c57c-957c-4054-87db-7bd4197f78d2)

在 utils/ 目录下，编译的时候找不到这两个文件。

**Comment by eachcan** [comment]
去掉这两个文件的引用，删除相应的代码就可以了。但是目前代码直接运行会有问题

**Comment by JelinYao** [comment]
漏了这两个文件，已经提交上去了。
